### ISSUE TITLE
Forwarded logs do not link to Azure Custom Device when they are migrated from legacy types

### ISSUE THREAD

**Issue by davidgallay** [dynatrace-oss/dynatrace-azure-log-forwarder#105]
As Dynatrace moves more managed Azure services to Custom Devices instead of discrete entity types, the linking between logs and entities is increasingly breaking. This is frustrating as logs and related events are linked to unavailable entities and can not use any of the metadata related to the correct custom devices. For example, log for an Azure SQL database will try to link to a legacy entity type instead of one of the new Custom Device types and clicking into the entity brings up a 404 page.

To resolve this, it would be nice if there was a parameter or property file that could be deployed to the Log Forwarder that would mark specific Azure entity types that have been migrated to new Custom Devices (since it would not be the same for all use cases or tenants) and have a lookup system in the forwarder to query for the right entity by typing metadata or name.

**Comment by piotrgorkowskidt** [comment]
Hey, thanks for reaching out. This is something we are thinking about, but currently there is no room for it due to priorities. We will have a ticket in our backlog, for sure, but no ETA.

**Comment by piotrgorkowskidt** [comment]
Hey, thanks for reaching out. This is something we are thinking about, but currently there is no room for it due to priorities. We will have a ticket in our backlog, for sure, but no ETA.
