### ISSUE TITLE
Option for container image to deploy to any compute target

### ISSUE THREAD

**Issue by joshua-hancox** [dynatrace-oss/dynatrace-azure-log-forwarder#114]
**Is your feature request related to a problem? Please describe.**
I'd prefer to manage all my own infrastructure as code (we use Terraform) rather than run a script to build infra.
I'd prefer to be able to deploy a container to our AKS cluster to get the same functionality provided by this function app setup.

**Describe the solution you'd like**
- dynatrace-azure-log-forwarder image pushed to docker hub
- Examples of configuration required by the app (env vars)
- Not essential, but ideally could also come with a helm chart or kubernetes deployment files

**Describe alternatives you've considered**
Deploying the function app as is.

**Additional context**
Would this app be scalable in case of high number of logs? Setting multiple replicas in a deployment?

**Comment by joaquinfilipic-dynatrace** [comment]
Hello, thanks for reaching out. 

This would be a nice enhancement. But I suggest using our [Community page](https://community.dynatrace.com/), since Product Management needs to check and prioritize it. I will close this issue and create an internal ticket to keep track of it, either way.
